title: Haenara Dev Blog
author: Haenara Shin
email: hamster12345@gmail.customize
description: > # this means to ignore newlines until "show_exerpts:"
  ì•ˆë“œë¡œì´ë“œ ê°œë°œì ì‹ í•´ë‚˜ë¼ì˜ ë¸”ë¡œê·¸
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://haenarashin.github.io/"
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Haenara Dev Blog
  tagline: ğŸ¤– Android App Developer
  date_format: " %Y-%b-%-d"
  style: black
  showNav: true
  showPicker: true

  # generate social links in footer
  social_links:
    github:  HaenaraShin
    linkedIn: in/í•´ë‚˜ë¼-ì‹ -a00548107/
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed